import express, { Request, Response } from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import Anthropic from '@anthropic-ai/sdk';
import { z } from 'zod';
import mongoose from 'mongoose';
import authRoutes from './server/routes/auth.js';

dotenv.config();

const app = express();
const PORT = process.env.PORT || 3001;

app.use(cors());
app.use(express.json());

// MongoDB Connection
const MONGO_URI = "mongodb://mohsinca2008_db_user:Dy3ByUQBYEBcBVEK@ac-ns1qczp-shard-00-00.refaywr.mongodb.net:27017,ac-ns1qczp-shard-00-01.refaywr.mongodb.net:27017,ac-ns1qczp-shard-00-02.refaywr.mongodb.net:27017/?ssl=true&replicaSet=atlas-12uv3v-shard-0&authSource=admin&appName=Cluster0";
mongoose.connect(MONGO_URI)
  .then(() => console.log('✅ Connected to MongoDB Cluster'))
  .catch((err) => console.error('❌ MongoDB connection error:', err));

// Auth Routes
app.use('/api/auth', authRoutes);

const apiKey = process.env.CLAUDE_API_KEY;

let anthropicClient: Anthropic | null = null;
if (apiKey && apiKey.startsWith('sk-ant-')) {
  anthropicClient = new Anthropic({ apiKey });
} else {
  console.warn('⚠️ Warning: CLAUDE_API_KEY is not set or invalid. Server running with fallback mode.');
}

// ----------------------------------------------------
// ZOD SCHEMAS FOR STRICT OUTPUT VALIDATION
// ----------------------------------------------------
const AISearchSchema = z.object({
  originalQuery: z.string().default(''),
  suggestedCategory: z.enum(['all', 'electronics', 'laptops', 'boots', 'bluetooth', 'hair-care', 'sports']).default('all'),
  maxPrice: z.number().optional(),
  minRating: z.number().optional(),
  extractedKeywords: z.array(z.string()).default([]),
  keyFeatures: z.array(z.string()).default([]),
  reasoning: z.string().default('AI evaluated matching criteria based on product attributes.'),
  matchedProductIds: z.array(z.string()).default([])
});

const AICompareSchema = z.object({
  productIds: z.array(z.string()).default([]),
  overview: z.string().default('Comparison overview generated by AI.'),
  featuresComparison: z.array(
    z.object({
      featureName: z.string(),
      values: z.record(z.string(), z.string())
    })
  ).default([]),
  prosAndCons: z.record(
    z.string(),
    z.object({
      pros: z.array(z.string()),
      cons: z.array(z.string())
    })
  ).default({}),
  bestFor: z.record(z.string(), z.string()).default({}),
  verdict: z.string().default('Selection recommendation based on specs and value.'),
  recommendedProductId: z.string().default('')
});

const AIReviewSchema = z.object({
  productId: z.string().default(''),
  sentimentScore: z.number().min(0).max(100).default(85),
  totalReviewsAnalyzed: z.number().default(0),
  keyPros: z.array(z.string()).default([]),
  keyCons: z.array(z.string()).default([]),
  summaryVerdict: z.string().default('Highly rated product according to customer feedback.')
});

// Helper function to query Claude with JSON enforcement
async function queryClaudeJSON(systemPrompt: string, userPrompt: string): Promise<any> {
  if (!anthropicClient) {
    throw new Error('Claude API client is not configured.');
  }

  const response = await anthropicClient.messages.create({
    model: 'claude-3-5-sonnet-20241022',
    max_tokens: 1024,
    temperature: 0.2,
    system: `${systemPrompt}\nIMPORTANT: Respond strictly with valid JSON. Do NOT include markdown codeblocks (\`\`\`json), commentary, or extra text before or after the JSON payload.`,
    messages: [
      {
        role: 'user',
        content: userPrompt
      }
    ]
  });

  const textBlock = response.content.find(c => c.type === 'text');
  if (!textBlock || !textBlock.text) {
    throw new Error('Empty response received from Claude API.');
  }

  const cleanedText = textBlock.text.trim().replace(/^```json\s*/i, '').replace(/\s*```$/i, '');
  return JSON.parse(cleanedText);
}

// ----------------------------------------------------
// 1. NATURAL LANGUAGE SEARCH ENDPOINT
// ----------------------------------------------------
app.post('/api/ai/search', async (req: Request, res: Response) => {
  try {
    const { query, products } = req.body;

    if (!query || typeof query !== 'string') {
      return res.status(400).json({ error: 'Valid query parameter is required.' });
    }

    if (!anthropicClient) {
      return res.status(503).json({
        fallback: true,
        message: 'Claude API key not available on server. Using fallback heuristic search.',
        data: null
      });
    }

    const catalogSummary = (products || []).map((p: any) => ({
      id: p.id,
      name: p.name,
      category: p.category,
      price: p.price,
      rating: p.rating?.rate,
      brand: p.brand,
      description: p.description
    }));

    const systemPrompt = `You are a high-performance e-commerce AI shopping assistant. Analyze the user's natural language shopping request and match it against the provided product catalog. Output JSON matching this schema:
{
  "originalQuery": string,
  "suggestedCategory": "all" | "electronics" | "laptops" | "boots" | "bluetooth" | "hair-care" | "sports",
  "maxPrice": number or null,
  "minRating": number or null,
  "extractedKeywords": string[],
  "keyFeatures": string[],
  "reasoning": string,
  "matchedProductIds": string[]
}`;

    const userPrompt = `User Query: "${query}"\n\nProduct Catalog:\n${JSON.stringify(catalogSummary, null, 2)}`;

    const rawResult = await queryClaudeJSON(systemPrompt, userPrompt);
    const validatedData = AISearchSchema.parse({ ...rawResult, originalQuery: query });

    return res.json({ success: true, data: validatedData });
  } catch (error: any) {
    console.error('Error in /api/ai/search:', error?.message || error);
    return res.status(500).json({
      success: false,
      fallback: true,
      error: error?.message || 'Failed to process AI search request.',
      data: null
    });
  }
});

// ----------------------------------------------------
// 2. PRODUCT COMPARISON ENDPOINT
// ----------------------------------------------------
app.post('/api/ai/compare', async (req: Request, res: Response) => {
  try {
    const { products } = req.body;

    if (!products || !Array.isArray(products) || products.length < 2) {
      return res.status(400).json({ error: 'At least 2 products are required for comparison.' });
    }

    if (!anthropicClient) {
      return res.status(503).json({
        fallback: true,
        message: 'Claude API key not configured. Using fallback local comparison.',
        data: null
      });
    }

    const comparisonInput = products.map((p: any) => ({
      id: p.id,
      name: p.name,
      brand: p.brand,
      price: p.price,
      originalPrice: p.originalPrice,
      rating: p.rating?.rate,
      specifications: p.specifications,
      description: p.description
    }));

    const systemPrompt = `You are an expert product reviewer and analyst. Compare the selected products objectively. Output strict JSON with key feature matrix, pros/cons for each product (by productId), target audience ("bestFor"), concise overview, and final verdict with recommendedProductId.
Format JSON:
{
  "productIds": string[],
  "overview": string,
  "featuresComparison": [
    { "featureName": string, "values": { "[productId]": string } }
  ],
  "prosAndCons": {
    "[productId]": { "pros": string[], "cons": string[] }
  },
  "bestFor": {
    "[productId]": string
  },
  "verdict": string,
  "recommendedProductId": string
}`;

    const userPrompt = `Compare these products:\n${JSON.stringify(comparisonInput, null, 2)}`;

    const rawResult = await queryClaudeJSON(systemPrompt, userPrompt);
    const validatedData = AICompareSchema.parse({
      ...rawResult,
      productIds: products.map((p: any) => p.id)
    });

    return res.json({ success: true, data: validatedData });
  } catch (error: any) {
    console.error('Error in /api/ai/compare:', error?.message || error);
    return res.status(500).json({
      success: false,
      fallback: true,
      error: error?.message || 'Failed to compare products via AI.',
      data: null
    });
  }
});

// ----------------------------------------------------
// 3. AI REVIEW SUMMARIES ENDPOINT
// ----------------------------------------------------
app.post('/api/ai/reviews', async (req: Request, res: Response) => {
  try {
    const { product, reviews } = req.body;

    if (!product || !product.id) {
      return res.status(400).json({ error: 'Valid product is required.' });
    }

    if (!anthropicClient) {
      return res.status(503).json({
        fallback: true,
        message: 'Claude API client not available. Using fallback review summary.',
        data: null
      });
    }

    const systemPrompt = `You are a customer review sentiment analyzer. Synthesize customer feedback into a concise JSON summary.
Output JSON format:
{
  "productId": string,
  "sentimentScore": number (0-100),
  "totalReviewsAnalyzed": number,
  "keyPros": string[],
  "keyCons": string[],
  "summaryVerdict": string
}`;

    const userPrompt = `Product: ${product.name} (${product.brand})
Rating: ${product.rating?.rate} stars out of 5 (${product.rating?.count} ratings)
Description: ${product.description}
Sample Customer Reviews:
${JSON.stringify(reviews || [], null, 2)}`;

    const rawResult = await queryClaudeJSON(systemPrompt, userPrompt);
    const validatedData = AIReviewSchema.parse({
      ...rawResult,
      productId: product.id,
      totalReviewsAnalyzed: (reviews || []).length || product.rating?.count || 10
    });

    return res.json({ success: true, data: validatedData });
  } catch (error: any) {
    console.error('Error in /api/ai/reviews:', error?.message || error);
    return res.status(500).json({
      success: false,
      fallback: true,
      error: error?.message || 'Failed to summarize reviews via AI.',
      data: null
    });
  }
});

// Start Express Server
app.listen(PORT, () => {
  console.log(`🚀 Zenith AI Backend Proxy Server running on http://localhost:${PORT}`);
});
